### ISSUE TITLE
python test.py gives "DLL load failed while importing defs: The specified procedure could not be found."

### ISSUE THREAD

**Issue by Atulsingh92** [GregDobby/Multi-Fidelity-High-Order-Gaussian-Processes-for-Physical-Simulation#1]
Hello, 

For python 3.8.5 on windows 10, 
TensorFlow 2.5.0 and numpy 1.20.2, I get the above mentioned error on running test.py file, with the complete error as follows, 

```
[runfile('C:/Users/aus1n19/scripts_local/DGP_hd/test.py', wdir='C:/Users/aus1n19/scripts_local/DGP_hd')
Traceback (most recent call last):

  File "C:\Users\aus1n19\scripts_local\DGP_hd\test.py", line 1, in <module>
    import EXPUtil as util

  File "C:\Users\aus1n19\scripts_local\DGP_hd\EXPUtil.py", line 4, in <module>
    import h5py

  File "C:\Users\aus1n19\Anaconda3\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version

  File "C:\Users\aus1n19\Anaconda3\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5

  File "h5py\h5.pyx", line 1, in init h5py.h5

ImportError: DLL load failed while importing defs: The specified procedure could not be found.]
```

**Comment by wzhut** [comment]
The code is implemented using tensorflow 1.4.1.

**Comment by zsdlightning** [comment]
We observed a similar problem when running with higher version of tensorflow. However, running with TF 1.5.0 or so is fine.
